Books = {

    1101         :'Inside the Machine: An Illustrated Introduction to Microprocessors and Computer Architecture',
    1102         :'Structure and Interpretation of Computer Programs',
    1103         :'Design Patterns: Elements of Reusable Object-Oriented Software',   
    1104         :'Code: The Hidden Language of Computer Hardware and Software',
    1105         :'Cracking the Coding Interview: 189 Programming Questions and Solutions',
    1106         :'Code Complete: A Practical Handbook of Software Construction',
    1107         :'Programming Pearls',
    1108         :'Algorithms to Live By: The Computer Science of Human Decisions',
    1109         :'Clean Code: A Handbook of Agile Software Craftsmanship',
    1110         :'Think Like a Programmer: An Introduction to Creative Problem Solving',       
    1111         :'Introduction to Algorithms',
    1112         :'Peopleware: Productive Projects and Teams',
    1113         :'Soft Skills: The software developer’s life manual ',
    1114         :'Rapid Development: Taming Wild Software Schedules',
    1115         :'Coders at Work: Reflections on the Craft of Programming',
    1116         :'The Passionate Programmer: Creating a Remarkable Career in Software Development',
    1117         :'Eloquent JavaScript: A Modern Introduction to Programming',
    1118         :'Modern PHP',
    1119         :'HTML and CSS: Design and Build Websites',
    1120         :'SQL Queries for Mere Mortals: A Hands-On Guide to Data Manipulation in SQL',
    1121         :'The Self-Taught Programmer: The Definitive Guide to Programming Professionally',
    1122         :'Swift Programming: The Big Nerd Ranch Guide',        
    1123         :'HTML and CSS: Design and Build Websites',
    1124         :'Java Concurrency in Practice',
    1125         :'SQL Queries for Mere Mortals: A Hands-On Guide to Data Manipulation in SQL',
    1126         :'Eloquent Ruby',
    1127         :'Introduction to Algorithms',
    1128         :'Swift Programming: The Big Nerd Ranch Guide',
    1129         :'Eloquent JavaScript: A Modern Introduction to Programming',
    1130         :'You Don’t Know JS Yet: Get Started',       
    1131         :'HTML and CSS: Design and Build Websites',
    1132         :'C# 7.0 in a Nutshell: The Definitive Reference',
    1133         :'Android Application Development All-in-One For Dummies',
    1134         :'Introduction to Algorithms',
    1135         :'Effective Objective-C 2.0: 52 Specific Ways to Improve Your IOS and OS X Programs',
    1136         :'Effective Java',
    1137         :'Practical C Programming: Why Does 2+2 = 5986?',
    1138         :'Python Crash Course: A Hands-On, Project-Based Introduction to Programming',
    1139         :'Modern PHP',
    1140         :'You Don’t Know JS Yet: Get Started',
    1141         :'Programming: Principles and Practice Using C++',
    1142         :'Java Concurrency in Practice',
    1143         :'Head First Python: A Brain-Friendly Guide',
    1144         :'Head First PHP & MySQL: A Brain-Friendly Guide',
    1145         :'Introduction to Algorithms',
    1146         :'C# in Depth',
    1147         :'HTML and CSS: Design and Build Websites',
    1148         :'R Cookbook: Proven Recipes for Data Analysis, Statistics, and Graphics',
    1149         :'SQL in 10 Minutes, Sams Teach Yourself',
    1150         :'Introduction to Algorithms',

    }

# print(Books)
# Books['1111']='####' #append value
# del Books["1101"] # delete value

# print(Books)